<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Version>2025.9</Version>
        <HsnSoftFrameworkVersion>2025.9.16</HsnSoftFrameworkVersion>
        <MicrosoftAspNetCorePackageVersion>9.0.10</MicrosoftAspNetCorePackageVersion>
        <MicrosoftEntityFrameworkCorePackageVersion>9.0.10</MicrosoftEntityFrameworkCorePackageVersion>
    </PropertyGroup>
</Project>