<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Eds.Shared.Hosting.Integration.Api</PackageId>
        <RootNamespace>Eds.Shared.Hosting.Integration.Api</RootNamespace>
        <Title>HsnSoft EDS Shared Hosting Integration Api</Title>
        <Description>HsnSoft EDS Shared Hosting Integration Api</Description>
        <PackageTags>HsnSoft EDS Shared Hosting Integration Api</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Eds.Shared.Hosting\Eds.Shared.Hosting.csproj"/>
        <ProjectReference Include="..\Eds.Shared.Helper\Eds.Shared.Helper.csproj"/>
    </ItemGroup>

</Project>
