<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Eds.Shared.Hosting.Microservices</PackageId>
        <RootNamespace>Eds.Shared.Hosting.Microservices</RootNamespace>
        <Title>HsnSoft EDS Shared Hosting Microservices</Title>
        <Description>HsnSoft EDS Shared Hosting Microservices</Description>
        <PackageTags>HsnSoft EDS Shared Hosting Microservices</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Eds.Shared.Contracts\Eds.Shared.Contracts.csproj" />
        <ProjectReference Include="..\Eds.Shared.Hosting\Eds.Shared.Hosting.csproj" />
    </ItemGroup>
</Project>
