<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props"/>
    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Eds.Shared.Hosting.Microservices</PackageId>
        <RootNamespace>Eds.Shared.Hosting.Microservices</RootNamespace>
        <Title>HsnSoft EDS Shared Hosting Microservices</Title>
        <Description>HsnSoft EDS Shared Hosting Microservices</Description>
        <PackageTags>HsnSoft EDS Shared Hosting Microservices</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0"/>
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="HsnSoft.Base.Caching.StackExchangeRedis" Version="$(HsnSoftFrameworkVersion)"/>
        <!--<ProjectReference Include="..\..\..\..\..\hsn-soft\base-framework\src\HsnSoft.Base.Caching.StackExchangeRedis\HsnSoft.Base.Caching.StackExchangeRedis.csproj" />-->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Eds.Shared.Contracts\Eds.Shared.Contracts.csproj"/>
        <ProjectReference Include="..\Eds.Shared.Hosting\Eds.Shared.Hosting.csproj"/>
    </ItemGroup>

</Project>
